<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BlueIdea.Reporting</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlueIdea.Domain\BlueIdea.Domain.csproj" />
    <ProjectReference Include="..\BlueIdea.Shared\BlueIdea.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>

</Project>
