export const DEFAULT_PASSWORD = 'Sk@2026';

export const ACCOUNTS = {
  admin: { username: 'admin', password: DEFAULT_PASSWORD },
  lanhdao: { username: 'lanhdao', password: DEFAULT_PASSWORD },
  tiepnhan: { username: 'tiepnhan', password: DEFAULT_PASSWORD },
  thuky: { username: 'thuky', password: DEFAULT_PASSWORD },
  chutich: { username: 'chutich', password: DEFAULT_PASSWORD },
  hoidong01: { username: 'hoidong01', password: DEFAULT_PASSWORD },
  hoidong02: { username: 'hoidong02', password: DEFAULT_PASSWORD },
  tacgia1: { username: 'gv.lan', password: DEFAULT_PASSWORD },
  tacgia2: { username: 'gv.hung', password: DEFAULT_PASSWORD },
  tacgia3: { username: 'gv.thuy', password: DEFAULT_PASSWORD },
  qtdonvi: { username: 'qtdonvi', password: DEFAULT_PASSWORD },
} as const;

export const API = {
  login: '/api/v1/xac-thuc/dang-nhap',
  me: '/api/v1/xac-thuc/toi',
  refreshToken: '/api/v1/xac-thuc/lam-moi-token',
  danhMuc: '/api/v1/danh-muc',
  dotDeNghi: '/api/v1/danh-muc/dot-de-nghi',
  donVi: '/api/v1/don-vi',
  sangKien: '/api/v1/sang-kien',
  xuLy: '/api/v1/xu-ly',
  danhGia: '/api/v1/danh-gia',
  hoiDong: '/api/v1/hoi-dong',
  quyTrinh: '/api/v1/quy-trinh',
  tieuChi: '/api/v1/tieu-chi',
  quyetDinh: '/api/v1/quyet-dinh',
  baoCao: '/api/v1/bao-cao',
  nguoiDung: '/api/v1/he-thong/nguoi-dung',
  vaiTro: '/api/v1/he-thong/vai-tro',
  cauHinh: '/api/v1/he-thong/cau-hinh',
  bieuMau: '/api/v1/danh-muc/bieu-mau-xuat',
  bieuMauThongKe: '/api/v1/danh-muc/bieu-mau-thong-ke',
  tepTin: '/api/v1/tep-tin',
  traCuu: '/api/v1/tra-cuu',
  congKhai: '/api/v1/cong-khai',
  nhatKy: '/api/v1/he-thong/nhat-ky',
  cauHinhMenu: '/api/v1/cau-hinh-menu',
  tichHop: '/api/v1/tich-hop',
  guiTin: '/api/v1/cau-hinh-gui-tin',
  chuKySo: '/api/v1/cau-hinh-chu-ky-so',
  ngayNghiLe: '/api/v1/ngay-nghi-le',
  saoLuu: '/api/v1/sao-luu',
  mauThongBao: '/api/v1/mau-thong-bao',
  khoaApiNgoai: '/api/v1/khoa-api-ngoai',
  nhatKyLoi: '/api/v1/he-thong/nhat-ky/loi',
  mfa: '/api/v1/xac-thuc/mfa',
  doiMatKhau: '/api/v1/xac-thuc/doi-mat-khau',
  quenMatKhau: '/api/v1/xac-thuc/quen-mat-khau',
  datLaiMatKhau: '/api/v1/xac-thuc/dat-lai-mat-khau',
} as const;

export const ROUTES = {
  login: '/dang-nhap',
  dashboard: '/',
  hoSoCuaToi: '/sang-kien/cua-toi',
  nopMoi: '/sang-kien/nop-moi',
  tiepNhan: '/tiep-nhan',
  xuLy: '/xu-ly',
  danhGia: '/danh-gia',
  hoiDong: '/hoi-dong',
  quyetDinh: '/quyet-dinh',
  traCuu: '/tra-cuu',
  congKhai: '/cong-khai/tra-cuu',
  baoCao: '/bao-cao',
  baoCaoTuyBien: '/bao-cao/tuy-bien',
  danhMuc: '/quan-tri/danh-muc',
  quyTrinh: '/quan-tri/quy-trinh',
  tieuChi: '/quan-tri/tieu-chi',
  nguoiDung: '/quan-tri/nguoi-dung',
  donVi: '/quan-tri/don-vi',
  vaiTro: '/quan-tri/vai-tro',
  cauHinh: '/quan-tri/cau-hinh',
  guiTin: '/quan-tri/gui-tin',
  chuKySo: '/quan-tri/chu-ky-so',
  nhatKy: '/quan-tri/nhat-ky',
  cauHinhMenu: '/quan-tri/cau-hinh/menu',
  lienThong: '/quan-tri/lien-thong',
  bieuMauXuat: '/quan-tri/danh-muc/bieu-mau-xuat',
  bieuMauThongKe: '/quan-tri/danh-muc/bieu-mau-thong-ke',
  dotDeNghi: '/quan-tri/danh-muc/dot-de-nghi',
  ngayNghiLe: '/quan-tri/danh-muc/ngay-nghi-le',
  saoLuu: '/quan-tri/sao-luu',
  mauThongBao: '/quan-tri/mau-thong-bao',
  capPheDuyet: '/quan-tri/danh-muc/cap-phe-duyet',
  doiMatKhau: '/doi-mat-khau',
  baoMatTaiKhoan: '/bao-mat-tai-khoan',
  quenMatKhau: '/quen-mat-khau',
  nhatKyDongBo: '/quan-tri/nhat-ky/dong-bo',
  nhatKyLoi: '/quan-tri/nhat-ky-loi',
  khoaApi: '/quan-tri/khoa-api',
} as const;
