<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BlueIdea.UnitTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlueIdea.Ai\BlueIdea.Ai.csproj" />
    <ProjectReference Include="..\..\src\BlueIdea.Application\BlueIdea.Application.csproj" />
    <ProjectReference Include="..\..\src\BlueIdea.Infrastructure\BlueIdea.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BlueIdea.Reporting\BlueIdea.Reporting.csproj" />
    <ProjectReference Include="..\..\src\BlueIdea.Domain\BlueIdea.Domain.csproj" />
    <ProjectReference Include="..\..\src\BlueIdea.Scoring\BlueIdea.Scoring.csproj" />
    <ProjectReference Include="..\..\src\BlueIdea.Shared\BlueIdea.Shared.csproj" />
    <ProjectReference Include="..\..\src\BlueIdea.Workflow\BlueIdea.Workflow.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

</Project>
